create table orders
(
    opco varchar(256),
    order_id varchar(256),
    uuid bigint default "identity"(5988815, 2, '1,1'::text),
    user_email varchar(512),
    user_name varchar(512),
    restaurant_name varchar(256),
    restaurant_location_number varchar(256),
    store_id varchar(256),
    zone_name varchar(256),
    time_zone varchar(256),
    city_manager_id bigint,
    is_disabled bigint,
    is_available bigint,
    supported_order_methods bigint,
    billing_contact_name varchar(256),
    billing_contact_email varchar(256),
    billing_contact_phone varchar(256),
    restaurant_email varchar(256),
    restaurant_order_email varchar(256),
    restaurant_phone_number varchar(256),
    restaurant_latitude varchar(256),
    restaurant_longitude varchar(256),
    restaurant_address1 varchar(256),
    restaurant_address2 varchar(256),
    restaurant_city varchar(256),
    restaurant_state varchar(256),
    restaurant_zip_code varchar(256),
    restaurant_country varchar(256),
    restaurant_credit_card_processing_rate double precision,
    restaurant_credit_card_processing_fee double precision,
    restaurant_delivery_percent double precision,
    driver_id bigint,
    driver_name varchar(256),
    driver_address varchar(256),
    driver_phone_number varchar(256),
    driver_hourly_rate varchar(256),
    order_time_local timestamp,
    order_date timestamp,
    order_week timestamp,
    order_month timestamp,
    order_type varchar(256),
    is_refunded boolean,
    final_status varchar(256),
    is_asap boolean,
    delivery_fee double precision,
    other_tax double precision,
    tips double precision,
    taxes double precision,
    refund_amount double precision,
    discount_amount double precision,
    promo_code varchar(256),
    commission double precision,
    time_to_acceptance double precision,
    total_restaurant_time double precision,
    delivery_time double precision,
    driver_wait_time double precision,
    lateness double precision,
    driver_ontime_for_pickup boolean,
    lat_delivery double precision,
    long_delivery double precision,
    dispatch_agent varchar(256)
)