create table orders
(
    opco varchar(256),
    order_id varchar(256),
    store_id varchar(256),
    city_manager_id bigint,
    restaurant_id bigint,
    driver_id bigint,
    user_id bigint,

    order_time_local timestamp,
    order_date timestamp,
    order_week timestamp,
    order_month timestamp,
    order_type varchar(256),
    store_id varchar(256),
    zone_name varchar(256),
    time_zone varchar(256),
    final_status varchar(256),
    is_asap boolean,
    is_refunded boolean,
    promo_code varchar(256),
    lat_delivery double precision,
    long_delivery double precision,
    dispatch_agent varchar(256),

    delivery_fee double precision,
    other_tax double precision,
    tips double precision,
    taxes double precision,
    refund_amount double precision,
    discount_amount double precision,
    commission double precision,

    time_to_acceptance double precision,
    delivery_time double precision,
    driver_wait_time double precision,
    lateness double precision,
    driver_ontime_for_pickup boolean,
    total_restaurant_time double precision,
)